spring:
  profiles: default
  data:
    mongodb:
      auditing: true
      databaseName: sticklet
      #uri: mongodb://localhost/sticklet
      host: 127.0.0.1
      port: 27017
      username: sticklet
      password: sticklet
#    cache:
#      ehcache:
#        config: classpath:ehcache.xml
logging: 
  level:
    org.springframework: WARN
    org.springframework.beans: INFO
    org.hibernate: INFO
    org.egr.authorware: DEBUG
server:
  port: 80
  session-timeout: 864000
login:
  enabled: true
  admin:
    password: admin
  register: true
debug:
  enabled: true
---
spring:
  profiles: live
  data:
    mongodb:
      auditing: true
      databaseName: sticklet_live
      host: 127.0.0.1
      port: 27017
      username:
      password:
server:
  session-timeout: 864000
  port: 80
  #port: 443 #for ssl
  #ssl:
  #  keyAlias: mykey
login:
  enabled: true
  register: false
debug:
  enabled: false
