spring:
  profiles: default
  data:
    mongodb:
      auditing: true
      databaseName: sticklet
      #uri: mongodb://localhost/sticklet
      host: 127.0.0.1
      port: 27017
      username: sticklet
      password: sticklet
#    cache:
#      ehcache:
#        config: classpath:ehcache.xml
logging: 
  level:
    org.springframework: WARN
    org.springframework.beans: INFO
    com.sticklet: TRACE
server:
  port: 80
  session-timeout: 864000
login:
  enabled: true
  admin:
    password: admin
  register:
    enabled: true
    confirmation: false
debug:
  enabled: true
email:
  enabled: false
  from: "admin@sticklet.com"
  password: 
  port: 587
---
spring:
  profiles: live
  data:
    mongodb:
      auditing: true
      databaseName: sticklet_live
      host: 127.0.0.1
      port: 27017
      username:
      password:
server:
  session-timeout: 864000 #10 days
  #session-timeout: 20000 #~6 hours
  port: 443 #for ssl
  #ssl:
  #  keyAlias:
login:
  enabled: true
  register:
    enabled: true
    confirmation: false
debug:
  enabled: false
email:
  enabled: true
  from: "admin@sticklet.com"
  password:
  port: 587
